version: '2'

services:
  harambeedevopsproject:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  harambeedevopsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  harambeedevops.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
